name: unilink_ethiopia
description: UniLink App
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  share_plus: ^10.0.0

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/home/
    - assets/images/profile/
    - assets/images/marketplace/
    - assets/images/auth/
